# Generated by Django 5.0.7 on 2026-09-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodzapp", "0013_rename_premium_enddate_nodzuser_premium_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
