# Generated by Django 5.0.7 on 2026-09-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodzapp", "0014_node_created_at_auto_now_add"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="video_content",
        ),
        migrations.RemoveField(
            model_name="node",
            name="video_link",
        ),
    ]
