# Generated by Django 5.0.7 on 2026-09-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodzapp", "0015_remove_youtube_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="ratio",
            field=models.FloatField(default=0),
        ),
    ]
