# Generated by Django 5.0.7 on 2026-09-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodzapp", "0016_node_ratio"),
    ]

    operations = [
        migrations.AddField(
            model_name="param",
            name="originLayer",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
