# Generated by Django 5.0.7 on 2026-10-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodzapp", "0017_param_origin_layer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invite",
        ),
    ]
