# Generated by Django 5.0.7 on 2026-10-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodzapp", "0019_premium_until_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodzuser",
            name="language",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
    ]
