# Generated by Django 5.0.7 on 2026-09-26 22:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("repo", models.CharField(max_length=200)),
                ("filename", models.CharField(max_length=300)),
                ("path", models.CharField(blank=True, max_length=500)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("embed", "Embed"),
                            ("audio", "Audio"),
                        ],
                        default="text",
                        max_length=6,
                    ),
                ),
                ("capabilities", models.JSONField(blank=True, default=list)),
                ("quant", models.CharField(blank=True, max_length=20)),
                ("size", models.PositiveBigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("downloading", "Downloading"),
                            ("ready", "Ready"),
                            ("error", "Error"),
                        ],
                        default="downloading",
                        max_length=12,
                    ),
                ),
                ("progress", models.FloatField(default=0)),
                ("error", models.TextField(blank=True)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["repo", "filename"],
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("code", "Code"),
                            ("image", "Image"),
                            ("tools", "Tools"),
                            ("orchestrator", "Orchestrator"),
                        ],
                        default="text",
                        max_length=12,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                ("system_prompt", models.TextField(blank=True)),
                ("tools_allowed", models.JSONField(blank=True, default=list)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["role", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="localmodel",
            constraint=models.UniqueConstraint(
                fields=("repo", "filename"), name="unique_model_file"
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agents",
                to="toolbox.localmodel",
            ),
        ),
        migrations.AddConstraint(
            model_name="agent",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_agent_name_per_owner"
            ),
        ),
    ]
