# Generated by Django 5.0.7 on 2026-09-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toolbox", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localmodel",
            name="progress",
        ),
        migrations.AddField(
            model_name="localmodel",
            name="downloaded",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="localmodel",
            name="label",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="localmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("downloading", "Downloading"),
                    ("ready", "Ready"),
                    ("error", "Error"),
                    ("cancelled", "Cancelled"),
                ],
                default="downloading",
                max_length=12,
            ),
        ),
    ]
