# Generated by Django 5.0.7 on 2026-09-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toolbox", "0002_library_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="memory",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
