# Generated by Django 5.0.7 on 2026-09-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toolbox", "0003_agent_memory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localmodel",
            name="kind",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("embed", "Embed"),
                    ("audio", "Audio"),
                    ("component", "Component"),
                ],
                default="text",
                max_length=10,
            ),
        ),
    ]
