# Generated by Django 5.0.7 on 2026-09-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toolbox", "0007_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="localmodel",
            name="api_key",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="localmodel",
            name="endpoint",
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
