# Generated by Django 5.0.7 on 2026-10-01 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toolbox", "0008_api_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="localmodel",
            name="unique_model_file",
        ),
        migrations.AddField(
            model_name="localmodel",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_models",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="localmodel",
            constraint=models.UniqueConstraint(
                fields=("owner", "repo", "filename"), name="unique_model_file"
            ),
        ),
    ]
