# Generated by Django 5.0.7 on 2026-10-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toolbox", "0009_personal_api_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="gallery",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
