# Generated by Django 5.0.7 on 2026-10-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toolbox", "0011_rooms"),
    ]

    operations = [
        migrations.AddField(
            model_name="localmodel",
            name="premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="preference",
            name="stripe_customer",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="preference",
            name="stripe_subscription",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
