# Generated by Django 5.0.7 on 2026-09-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("file", "File"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("model3d", "Model3D"),
                    ("code", "Code"),
                    ("prompt", "Prompt"),
                    ("drawing", "Drawing"),
                ],
                default="text",
                max_length=8,
            ),
        ),
    ]
