"""
Django settings for nodz project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '0') == '1'

if not SECRET_KEY or (not DEBUG and SECRET_KEY.startswith('dev-only')):
    raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set (see .env.example)')

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h]

# Préfixe d'URL quand Nodz est servi sous un chemin (ex. /nodz derrière le nginx de paintit).
FORCE_SCRIPT_NAME = os.environ.get('NODZ_URL_PREFIX', '').rstrip('/') or None
# Noms propres à Nodz : sur un domaine partagé, sessionid/csrftoken entreraient en collision.
SESSION_COOKIE_NAME = 'nodz_sessionid'
CSRF_COOKIE_NAME = 'nodz_csrftoken'
SESSION_COOKIE_PATH = CSRF_COOKIE_PATH = (FORCE_SCRIPT_NAME or '') + '/'
CSRF_TRUSTED_ORIGINS = [o for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o]

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # HSTS volontairement absent en test (irréversible côté navigateurs) ; nginx redirige vers HTTPS ;
    # X_FRAME_OPTIONS reste SAMEORIGIN car Nodz s'affiche lui-même en iframe.
    SILENCED_SYSTEM_CHECKS = ['security.W004', 'security.W008', 'security.W019']


# Application definition

INSTALLED_APPS = [
    "daphne",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'nodzapp',
    'graph',
    'toolbox',
    # 'widget_tweaks',
    # 'django_tex',
    # 'wkhtmltopdf',
    'channels',
]

ASGI_APPLICATION = 'nodz.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# # Configure Channels Redis as channel layer
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],  # Adjust this if your Redis server runs on a different host/port
#         },
#     },
# }


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'nodz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'nodzapp.context_processors.nodz_base',
            ],
        },
    },
]

WSGI_APPLICATION = 'nodz.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('SQLITE_PATH') or BASE_DIR / 'db.sqlite3',
    }
}

DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # Optional, also 10 MB


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = (FORCE_SCRIPT_NAME or '') + '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'nodzapp/static'),
    # Add more app static directories if necessary
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}
MEDIA_URL = (FORCE_SCRIPT_NAME or '') + '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'nodzapp/media')

# Boîte à outils IA (modèles locaux GGUF téléchargés depuis Hugging Face).
MODELS_DIR = Path(os.environ.get('MODELS_DIR') or BASE_DIR / 'var' / 'models')
HF_TOKEN = os.environ.get('HF_TOKEN', '')
# Défauts du serveur, comme iAqua : « auto » calcule au chargement (contexte, couches GPU selon la VRAM libre).
LLM_CTX = os.environ.get('LLM_CTX', 'auto')
LLM_GPU_LAYERS = os.environ.get('LLM_GPU_LAYERS', 'auto')  # auto, max ou un nombre
LLM_THREADS = int(os.environ.get('LLM_THREADS', '0'))  # 0 = cœurs physiques
# Outils portés d'iAqua : espace de travail par utilisateur, environnement Python, shell et MCP (administrateur)
WORKSPACE_DIR = Path(os.environ.get('WORKSPACE_DIR') or BASE_DIR / 'var' / 'workspace')
GUARDIAN_PYENV = Path(os.environ.get('GUARDIAN_PYENV') or BASE_DIR / 'var' / 'pyenv')
GUARDIAN_SHELL = os.environ.get('GUARDIAN_SHELL', '0') == '1'  # shell, Python et outils forgés : coupés par défaut
MCP_SERVERS = os.environ.get('MCP_SERVERS', '')  # JSON : {"nom": {"url": "https://…/mcp", "headers": {}, "description": "…"}}
SD_BIN = os.environ.get('SD_BIN', '')  # stable-diffusion.cpp (vide = cherché dans le PATH)
GUARDIAN_WEB = os.environ.get('GUARDIAN_WEB', '1') == '1'  # recherche et lecture web par le Gardien
BRAVE_API_KEY = os.environ.get('BRAVE_API_KEY', '')  # recherche web par Brave Search (facultatif, la plus fiable)
SEARXNG_URL = os.environ.get('SEARXNG_URL', '').rstrip('/')  # instance SearXNG (facultatif, peut être locale)
GUARDIAN_WORKERS = int(os.environ.get('GUARDIAN_WORKERS', '1'))  # demandes au Gardien traitées en même temps
GUARDIAN_QUEUE = int(os.environ.get('GUARDIAN_QUEUE', '8'))  # demandes en attente au plus

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO')},
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'nodzapp.NodzUser'

LOGIN_REDIRECT_URL = 'universe'
LOGOUT_REDIRECT_URL = 'home'


# Add your email configuration
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_BACKEND = (
    'django.core.mail.backends.smtp.EmailBackend'
    if EMAIL_HOST
    else 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', '1') == '1'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'nodz@localhost')

STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
